Feature/lab 2
qolep/effective.band.marvel.ios pull request #1
Opened 2022-12-05 11:09 UTC by qolep

2022-12-05 12:24 UTC, andrejkrasnov requested changes
поправь комменты и причеши код  избавившись от форсанврапов

2022-12-05 12:24 UTC, andrejkrasnov commented on Podfile
> + pod 'TinyConstraints'
убрать лишнюю зависимость TinyConstraints

2022-12-05 12:24 UTC, andrejkrasnov commented on marvel_app_labs/CollectionViewCard.swift
> +    /*func setup(heroData: HeroModel) {
закомменченный код лучше почистиь

2022-12-05 12:24 UTC, andrejkrasnov commented on marvel_app_labs/ListViewController.swift
> +    private let titleTextLabel: UILabel = {
nit: text можно было не писать

2022-12-05 12:24 UTC, andrejkrasnov commented on marvel_app_labs/ListViewController.swift
> +        layout.itemSize = CGSize(width: UIScreen.main.bounds.width - 100,
private exetension ListViewController{

      enum Static {
      static var collectionViewLayoutInset: UIEdgeInsets { UIEdgeInsets(top: 0, left: 60, bottom: 0, right: 60)  }
      }
}

2022-12-05 12:24 UTC, andrejkrasnov commented on marvel_app_labs/ListViewController.swift
> +        navigationController?.navigationBar.tintColor = .white
если хотел скрыть навбар есть метод setNavigationBarHidden(_isHidden, animation: )

2022-12-06 08:04 UTC, qolep commented on Podfile
> + pod 'TinyConstraints'
Поправил комменты.

2022-12-16 05:03 UTC, merged